
project:
  type: website
  render:
    - "**/*.qmd"
    - "**/*.ipynb"

website:
  title: "Remise à Niveau Informatique"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: SQL
        menu: 
          - href: docs/sql/sql.qmd
            text: "Introduction à SQL"
          - href: docs/sql/DBeaver.qmd
            text: "DBeaver"
      - text: Python
        menu: 
          - href: docs/python/python.qmd
            text: "Introduction à Python"
      - href: docs/POO/POO.qmd
        text: POO
      - href: docs/UML/UML.qmd
        text: UML
    right:
      - icon: github
        href: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau
        target: "_blank"        
  page-footer:
    right: |
      Website built with <a href=https://quarto.org/ target="_blank">Quarto</a><br>
      <a href=https://github.com/ludo2ne/ENSAI-2A-Big-Data target="_blank">Source code</a>
  repo-url: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau
  repo-branch: main
  issue-url: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau/issues/new
  repo-actions: [edit, issue]
  downloads: [pdf]

format:
  html:
    theme: 
      dark: solar
      light: cosmo
    css: styles.css



