
project:
  type: website
  render:
    - "**/*.qmd"
    - "**/*.ipynb"

website:
  title: "Remise à Niveau Informatique"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: SQL
        menu: 
          - href: docs/sql/sql.qmd
            text: "Introduction à SQL"
          - href: docs/sql/DBeaver.qmd
            text: "DBeaver"
      - text: Python
        menu: 
          - href: docs/python/python-cours.qmd
            text: "Introduction à Python"
          - href: docs/python/01-types-et-variables.qmd
            text: "Types et Variables"
          - href: docs/python/02-listes-et-dictionnaires.qmd
            text: "Listes et Dictionnaires"
          - href: docs/python/03-tests-et-boucles.qmd
            text: "Tests et Boucles"
          - href: docs/python/04-fonctions.qmd
            text: "Fonctions"
          - href: docs/python/05-POO-introduction.qmd
            text: "Introduction à la POO"
      - href: docs/POO/POO.qmd
        text: POO
      - href: docs/UML/UML.qmd
        text: UML
      - text: Outils
        menu: 
          - href: docs/outils/outils.qmd
            text: "Outils"
          - href: docs/outils/VM.qmd
            text: "VM"
          - href: docs/outils/Git.qmd
            text: "Git"
          - href: docs/outils/Git TP.qmd
            text: "Git TP"
          - href: docs/outils/VSCode.qmd
            text: "Visual Studio Code"
    right:
      - icon: github
        href: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau
        target: "_blank"
  reader-mode: true      
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Source code](https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau){.external target="_blank"}
  repo-url: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau
  repo-branch: main
  issue-url: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau/issues/new
  repo-actions: [edit, issue]

format:
  html:
    theme: 
      dark: solar
      light: cosmo
    css: styles.css



