
project:
  type: website
  render:
    - "**/*.qmd"
    - "**/*.ipynb"

website:
  title: "Remise à Niveau Informatique"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: Home
      - text: SQL
        menu: 
          - href: docs/sql/sql-cours.qmd
            text: "Introduction à SQL"
          - href: docs/sql/sql-exercice.qmd
            text: "Exercice SQL"
      - text: Python
        menu: 
          - href: docs/python/python-cours.qmd
            text: "Introduction à Python"
          - href: docs/python/python-notebooks.qmd
            text: "Notebooks Python"
          - href: docs/python/01-types-et-variables.qmd
            text: "Types et Variables"
          - href: docs/python/02-listes-et-dictionnaires.qmd
            text: "Listes et Dictionnaires"
          - href: docs/python/03-tests-et-boucles.qmd
            text: "Tests et Boucles"
          - href: docs/python/04-fonctions.qmd
            text: "Fonctions"
          - href: docs/python/05-POO-introduction.qmd
            text: "Introduction à la POO"
          - href: docs/python/correction.qmd
            text: "Correction"
      - text: POO
        menu:
          - href: docs/POO/poo-cours.qmd
            text: "Introduction à la POO"
          - href: docs/POO/poo-exercice.qmd
            text: "Exercices POO"
      - href: docs/UML/UML.qmd
        text: UML
      - text: Outils
        menu: 
          - href: docs/outils/outils.qmd
            text: "Outils"
          - href: docs/outils/Bash.qmd
            text: "Bash"
          - href: docs/outils/DBeaver.qmd
            text: "DBeaver"
          - href: docs/outils/LaTeX.qmd
            text: "LaTeX"
          - href: docs/outils/Markdown.qmd
            text: "Markdown"
          - href: docs/outils/VSCode.qmd
            text: "Visual Studio Code"
          - href: docs/outils/VM.qmd
            text: "VM"
          - href: docs/outils/YAML.qmd
            text: "YAML"
    right:
      - text: Examens
        menu: 
          - href: docs/annales/examen-2024.qmd
            text: "Examen 2024"
      - icon: github
        href: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau
        target: "_blank"
  reader-mode: true
  page-footer:
    right: |
      Website built with [Quarto](https://quarto.org/){.external target="_blank"} <br>
      [Source code](https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau){.external target="_blank"}
  repo-url: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau
  repo-branch: main
  issue-url: https://github.com/ludo2ne/ENSAI-2A-Remise-a-niveau/issues/new
  repo-actions: [edit, issue]

format:
  html:
    theme: 
      dark: solar
      light: cosmo
    css: styles.css



